##### <font color=#A0A0A0>
##### ════════════════════════════════════════════════════════
#####     🦾🤖 **CREATING A NEURAL NETWORK FROM SCRATCH**
##### ════════════════════════════════════════════════════════ </font>

#### 🎯 Project Objetive
Make a general neural network with some of the most important configurations. Test it with different data sets and track it's performance with differents hyperparameters

In [2]:
#import used pakages
import sys
import os
import random

if 'convolutional_net' in sys.modules:
    del sys.modules['convolutional_net']
    
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from keras.datasets import mnist
from keras.datasets import fashion_mnist
import numpy as np 
from sklearn.model_selection import train_test_split
from convolutional_net import conv2d
import matplotlib.pyplot as plt

SyntaxError: non-default argument follows default argument (convolutional_net.py, line 30)

#### <font color=#A0A0A0> **🔘 Selection of hyperparameters**</font>

#### <font color=#A0A0A0> **🧐 Performance Summary**</font>

#### <font color=#A0A0A0> **🧐✅ Conclusions**</font>

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
X_train[0].shape

(28, 28)

In [ ]:
image = np.random.rand(4, 4)
kernel = np.random.normal(loc=0, scale=1, size=(2, 2))
conv2d(image, kernel)

array([[ 0.16836206,  0.91708487,  0.57155967],
       [ 0.43871061, -0.41442096,  0.18948589],
       [ 0.70925232,  0.21911602,  0.59589066]])

In [ ]:
np.random.normal(loc=0, scale=1, size=(2, 2, 2))

array([[[1.30220072, 1.86377271],
        [0.07109067, 0.825156  ]],

       [[0.44227715, 0.69548004],
        [1.00443613, 0.45836072]]])

In [ ]:
import numpy as np
layers=4
weights = np.random.randn(1,layers)/np.sqrt(layers)
weights

array([ 1.50672703,  0.64287111, -0.59387422,  0.06053933])

In [15]:
a = np.array([[[1,2],[1,6],[9,5]],[[11,2],[1,6],[9,10]]])
np.argmax(a)

6

In [22]:
pool_size = 2
data_rows, data_cols = data.shape
pool_data_rows = data_rows//pool_size
pool_data_cols = data_cols//pool_size

max_pooling = np.zeros((pool_data_rows, pool_data_cols))

for i in range(0, data_rows - pool_size+1, pool_size):
    for j in range(0, data_cols - pool_size+1, pool_size):
        a = i//pool_size
        b = j//pool_size
        max_pooling[a, b] = np.max(data[i:i+pool_size, j:j+pool_size])

max_pooling

array([[0.7525783 , 0.99427284],
       [0.78414284, 0.68565595]])

In [ ]:
kernel

array([[ 0.95915174, -0.61178145],
       [-0.52804561,  0.75621641]])

In [ ]:
def conv2d(image, kernel, padding=0, stride=1):
    padding=1
    rows_img, col_img = image.shape
    padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
    padded_rows_img, padded_cols_img = padded_img.shape
    padded_img[padding:padded_rows_img-padding, padding:padded_cols_img-padding] = image
    kernel_rows, kernel_cols = kernel.shape
    img_filter_rows = padded_rows_img-kernel_rows
    img_filter_cols = padded_cols_img-kernel_cols

    image_filter = np.zeros((img_filter_rows, img_filter_cols))
    
    for i in range(padded_rows_img-kernel_rows+1):
        for j in range(padded_cols_img-kernel_cols+1):
            image_filter[i, j] = padded_img[i:img_filter_rows, j:img_filter_cols]*kernel

    return image_filter

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
image = X_train[0]
padding=1
col_img, rows_img = image.shape
padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
padded_img[padding:image.shape[0]+padding, padding:image.shape[1]+padding] = image
padded_img.shape

(30, 30)

In [ ]:
kernels = [[[1, 2,3],[1, 2,3],[1, 2,3]], [[1, 1, 1],[1, 1, 1],[1, 1, 1]], [[2,2,2],[2,2,2],[2,2,2]]]
bias = np.array([1,2,3])

for i, j in enumerate(kernels):
    print(i)
    print(j)

0
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
1
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
2
[[2, 2, 2], [2, 2, 2], [2, 2, 2]]


In [ ]:
np.array(bias>0, dtype=np.float64)

array([1., 1., 1.])

In [ ]:
import numpy as np

# 1. Define the image and padding
# Example image (a 5x5 matrix)
image = np.random.rand(2, 4)
padding = 2

# 2. Get the new dimensions of the padded image
rows_img, cols_img = image.shape
new_rows = rows_img + padding * 2
new_cols = cols_img + padding * 2

# 3. Create a new, larger matrix filled with zeros
padded_image = np.zeros((new_rows, new_cols))

# 4. Place the original image in the center of the new matrix
# The slice starts at 'padding' and goes up to 'new_rows - padding'
padded_image[padding:new_rows - padding, padding:new_cols - padding] = image

print("Original Image:\n", image)
print("\n Padded Image:\n", padded_image)

Original Image:
 [[0.2431393  0.51969049 0.05839192 0.7396655 ]
 [0.04077804 0.08833915 0.99933226 0.67465722]]

 Padded Image:
 [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.2431393  0.51969049 0.05839192 0.7396655
  0.         0.        ]
 [0.         0.         0.04077804 0.08833915 0.99933226 0.67465722
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [ ]:
padded_image.shape

(6, 8)