##### <font color=#A0A0A0>
##### ════════════════════════════════════════════════════════
#####     🦾🤖 **CREATING A NEURAL NETWORK FROM SCRATCH**
##### ════════════════════════════════════════════════════════ </font>

#### 🎯 Project Objetive
Make a general neural network with some of the most important configurations. Test it with different data sets and track it's performance with differents hyperparameters

In [103]:
#import used pakages
import sys
import os
import random

if 'convolutional_net' in sys.modules:
    del sys.modules['convolutional_net']
    
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from keras.datasets import mnist
from keras.datasets import fashion_mnist
import numpy as np 
from sklearn.model_selection import train_test_split
from convolutional_net import Network,ConvLayer ,PoolingLayer, FlattenLayer, DenseLayer
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical

In [104]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255

y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

In [105]:
layers = [
    ConvLayer(kernel_size=2, filters=4, padding=1),
    PoolingLayer(2),
    FlattenLayer(),
    DenseLayer(128, activation='relu'),
    DenseLayer(10, activation='softmax')
]

model = Network(layers)
model.train(x_train, y_train, 20)

(29999, 13, 4)
(1559948,)


IndexError: tuple index out of range

#### <font color=#A0A0A0> **🔘 Selection of hyperparameters**</font>

#### <font color=#A0A0A0> **🧐 Performance Summary**</font>

#### <font color=#A0A0A0> **🧐✅ Conclusions**</font>

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
X_train[0].shape

(28, 28)

In [ ]:
image = np.random.rand(4, 4)
kernel = np.random.normal(loc=0, scale=1, size=(2, 2))
conv2d(image, kernel)

NameError: name 'conv2d' is not defined

In [ ]:
input = np.random.normal(loc=0, scale=1, size=(2, 4, 4))
input_shape = input.shape
output_gradient = np.random.normal(loc=0, scale=1, size=(2, 2, 2))
mask_gradient = np.array([[1,5,9,13,17,21,25,29]])

In [ ]:
input

array([[[-0.25448047,  1.3685209 ,  1.18835268, -0.28584127],
        [ 0.11143585,  0.80550693,  0.04999749, -0.95414228],
        [-1.05754925, -0.93536654,  1.77548076,  0.92877816],
        [-2.11175165,  0.40510067, -0.08400911,  0.639113  ]],

       [[-0.11087243, -0.61697637,  1.26038903, -0.8100615 ],
        [-1.79421637,  0.22899221,  0.60927435, -1.09216568],
        [ 0.69261861, -1.0546534 , -1.45315646, -0.20403805],
        [ 0.45290048,  0.12487262, -0.71931902,  0.79659953]]])

In [ ]:
mask_flat = mask_gradient.flatten()
output_gradient_flat = output_gradient.flatten()
input_gradient_flat = np.zeros(input_shape).flatten()

for i in range(len(output_gradient_flat)):
    gradient_value = output_gradient_flat[i]
    max_index_flat = mask_flat[i]
    input_gradient_flat[max_index_flat] = gradient_value

input_gradient = input_gradient_flat.reshape(input_shape)
input_gradient

array([[[ 0.        ,  0.83034607,  0.        ,  0.        ],
        [ 0.        , -1.30694064,  0.        ,  0.        ],
        [ 0.        , -0.57266574,  0.        ,  0.        ],
        [ 0.        ,  0.74008883,  0.        ,  0.        ]],

       [[ 0.        ,  0.28749159,  0.        ,  0.        ],
        [ 0.        , -1.17911572,  0.        ,  0.        ],
        [ 0.        , -2.20168914,  0.        ,  0.        ],
        [ 0.        ,  0.85098851,  0.        ,  0.        ]]])

In [ ]:
input_shape

(4, 4, 2)

In [ ]:
2%2

0

In [ ]:
a = np.array([[7,1],[8,6]])
np.argmax(a)

2

In [ ]:
3%2

1

In [ ]:
import numpy as np
layers=2
weights = np.random.randn(layers,layers)/np.sqrt(layers)
np.pad(weights, 2, mode='constant')

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.72371297,  0.15031481,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.62619571,  1.11849715,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [ ]:
a = np.array([[[1,2],[1,6],[9,5]],[[11,2],[1,6],[9,10]]])
np.argmax(a)

6

In [ ]:
pool_size = 2
data_rows, data_cols = data.shape
pool_data_rows = data_rows//pool_size
pool_data_cols = data_cols//pool_size

max_pooling = np.zeros((pool_data_rows, pool_data_cols))

for i in range(0, data_rows - pool_size+1, pool_size):
    for j in range(0, data_cols - pool_size+1, pool_size):
        a = i//pool_size
        b = j//pool_size
        max_pooling[a, b] = np.max(data[i:i+pool_size, j:j+pool_size])

max_pooling

array([[0.7525783 , 0.99427284],
       [0.78414284, 0.68565595]])

In [ ]:
kernel

array([[ 0.95915174, -0.61178145],
       [-0.52804561,  0.75621641]])

In [ ]:
def conv2d(image, kernel, padding=0, stride=1):
    padding=1
    rows_img, col_img = image.shape
    padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
    padded_rows_img, padded_cols_img = padded_img.shape
    padded_img[padding:padded_rows_img-padding, padding:padded_cols_img-padding] = image
    kernel_rows, kernel_cols = kernel.shape
    img_filter_rows = padded_rows_img-kernel_rows
    img_filter_cols = padded_cols_img-kernel_cols

    image_filter = np.zeros((img_filter_rows, img_filter_cols))
    
    for i in range(padded_rows_img-kernel_rows+1):
        for j in range(padded_cols_img-kernel_cols+1):
            image_filter[i, j] = padded_img[i:img_filter_rows, j:img_filter_cols]*kernel

    return image_filter

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
image = X_train[0]
padding=1
col_img, rows_img = image.shape
padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
padded_img[padding:image.shape[0]+padding, padding:image.shape[1]+padding] = image
padded_img.shape

(30, 30)

In [ ]:
kernels = [[[1, 2,3],[1, 2,3],[1, 2,3]], [[1, 1, 1],[1, 1, 1],[1, 1, 1]], [[2,2,2],[2,2,2],[2,2,2]]]
bias = np.array([1,2,3])

for i, j in enumerate(kernels):
    print(i)
    print(j)

0
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
1
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
2
[[2, 2, 2], [2, 2, 2], [2, 2, 2]]


In [ ]:
np.array(bias>0, dtype=np.float64)

array([1., 1., 1.])

In [ ]:
import numpy as np

# 1. Define the image and padding
# Example image (a 5x5 matrix)
image = np.random.rand(2, 4)
padding = 2

# 2. Get the new dimensions of the padded image
rows_img, cols_img = image.shape
new_rows = rows_img + padding * 2
new_cols = cols_img + padding * 2

# 3. Create a new, larger matrix filled with zeros
padded_image = np.zeros((new_rows, new_cols))

# 4. Place the original image in the center of the new matrix
# The slice starts at 'padding' and goes up to 'new_rows - padding'
padded_image[padding:new_rows - padding, padding:new_cols - padding] = image

print("Original Image:\n", image)
print("\n Padded Image:\n", padded_image)

Original Image:
 [[0.2431393  0.51969049 0.05839192 0.7396655 ]
 [0.04077804 0.08833915 0.99933226 0.67465722]]

 Padded Image:
 [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.2431393  0.51969049 0.05839192 0.7396655
  0.         0.        ]
 [0.         0.         0.04077804 0.08833915 0.99933226 0.67465722
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [ ]:
padded_image.shape

(6, 8)