##### <font color=#A0A0A0>
##### ════════════════════════════════════════════════════════
#####     🦾🤖 **CREATING A NEURAL NETWORK FROM SCRATCH**
##### ════════════════════════════════════════════════════════ </font>

#### 🎯 Project Objetive
Make a general neural network with some of the most important configurations. Test it with different data sets and track it's performance with differents hyperparameters

In [ ]:
#import used pakages
import sys
import os
import random

if 'convolutional_net' in sys.modules:
    del sys.modules['convolutional_net']
    
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from keras.datasets import mnist
from keras.datasets import fashion_mnist
import numpy as np 
from sklearn.model_selection import train_test_split
from convolutional_net import conv2d
import matplotlib.pyplot as plt

#### <font color=#A0A0A0> **🔘 Selection of hyperparameters**</font>

#### <font color=#A0A0A0> **🧐 Performance Summary**</font>

#### <font color=#A0A0A0> **🧐✅ Conclusions**</font>

In [5]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [12]:
X_train[0].shape

(28, 28)

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
image = X_train[0]
padding=1
col_img, rows_img = image.shape
padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
padded_img[padding:image.shape[0]+padding, padding:image.shape[1]+padding] = image
padded_img.shape

(30, 30)

In [28]:
import numpy as np

# 1. Define the image and padding
# Example image (a 5x5 matrix)
image = np.random.rand(5, 5)
padding = 1

# 2. Get the new dimensions of the padded image
rows_img, cols_img = image.shape
new_rows = rows_img + padding * 2
new_cols = cols_img + padding * 2

# 3. Create a new, larger matrix filled with zeros
padded_image = np.zeros((new_rows, new_cols))

# 4. Place the original image in the center of the new matrix
# The slice starts at 'padding' and goes up to 'new_rows - padding'
padded_image[padding:new_rows - padding, padding:new_cols - padding] = image

print("Original Image:\n", image)
print("\n Padded Image:\n", padded_image)

Original Image:
 [[0.42026681 0.37941979 0.64511583 0.46311797 0.43827757]
 [0.55291798 0.25895821 0.85993633 0.17200719 0.7664816 ]
 [0.16976807 0.55588955 0.9912672  0.23959979 0.85046617]
 [0.96903732 0.22480731 0.85697048 0.02305185 0.3447207 ]
 [0.41748223 0.17882347 0.03014081 0.39858623 0.85827677]]

 Padded Image:
 [[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.42026681 0.37941979 0.64511583 0.46311797 0.43827757
  0.        ]
 [0.         0.55291798 0.25895821 0.85993633 0.17200719 0.7664816
  0.        ]
 [0.         0.16976807 0.55588955 0.9912672  0.23959979 0.85046617
  0.        ]
 [0.         0.96903732 0.22480731 0.85697048 0.02305185 0.3447207
  0.        ]
 [0.         0.41748223 0.17882347 0.03014081 0.39858623 0.85827677
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]
