##### <font color=#A0A0A0>
##### ════════════════════════════════════════════════════════
#####     🦾🤖 **CREATING A NEURAL NETWORK FROM SCRATCH**
##### ════════════════════════════════════════════════════════ </font>

#### 🎯 Project Objetive
Make a general neural network with some of the most important configurations. Test it with different data sets and track it's performance with differents hyperparameters

In [133]:
#import used pakages
import sys
import os
import random

if 'convolutional_net' in sys.modules:
    del sys.modules['convolutional_net']
    
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))
from keras.datasets import mnist
from keras.datasets import fashion_mnist
import numpy as np 
from sklearn.model_selection import train_test_split
from convolutional_net import conv2d
import matplotlib.pyplot as plt

#### <font color=#A0A0A0> **🔘 Selection of hyperparameters**</font>

#### <font color=#A0A0A0> **🧐 Performance Summary**</font>

#### <font color=#A0A0A0> **🧐✅ Conclusions**</font>

In [134]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [135]:
X_train[0].shape

(28, 28)

In [136]:
image = np.random.rand(4, 4)
kernel = np.random.normal(loc=0, scale=1, size=(2, 2))
conv2d(image, kernel)

array([[ 0.16836206,  0.91708487,  0.57155967],
       [ 0.43871061, -0.41442096,  0.18948589],
       [ 0.70925232,  0.21911602,  0.59589066]])

In [145]:
np.random.normal(loc=0, scale=1, size=(2, 2, 2))

array([[[1.30220072, 1.86377271],
        [0.07109067, 0.825156  ]],

       [[0.44227715, 0.69548004],
        [1.00443613, 0.45836072]]])

In [137]:
image

array([[0.85584187, 0.88627675, 0.5565247 , 0.11461032],
       [0.44643865, 0.1658619 , 0.65466063, 0.59979546],
       [0.82936283, 0.72720033, 0.27901601, 0.10029393],
       [0.52739604, 0.84254235, 0.18145355, 0.64194016]])

In [138]:
kernel

array([[ 0.95915174, -0.61178145],
       [-0.52804561,  0.75621641]])

In [139]:
def conv2d(image, kernel, padding=0, stride=1):
    padding=1
    rows_img, col_img = image.shape
    padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
    padded_rows_img, padded_cols_img = padded_img.shape
    padded_img[padding:padded_rows_img-padding, padding:padded_cols_img-padding] = image
    kernel_rows, kernel_cols = kernel.shape
    img_filter_rows = padded_rows_img-kernel_rows
    img_filter_cols = padded_cols_img-kernel_cols

    image_filter = np.zeros((img_filter_rows, img_filter_cols))
    
    for i in range(padded_rows_img-kernel_rows+1):
        for j in range(padded_cols_img-kernel_cols+1):
            image_filter[i, j] = padded_img[i:img_filter_rows, j:img_filter_cols]*kernel

    return image_filter

In [140]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [141]:
image = X_train[0]
padding=1
col_img, rows_img = image.shape
padded_img = np.zeros((rows_img+padding*2,col_img+padding*2))
padded_img[padding:image.shape[0]+padding, padding:image.shape[1]+padding] = image
padded_img.shape

(30, 30)

In [142]:
import numpy as np

# 1. Define the image and padding
# Example image (a 5x5 matrix)
image = np.random.rand(2, 4)
padding = 2

# 2. Get the new dimensions of the padded image
rows_img, cols_img = image.shape
new_rows = rows_img + padding * 2
new_cols = cols_img + padding * 2

# 3. Create a new, larger matrix filled with zeros
padded_image = np.zeros((new_rows, new_cols))

# 4. Place the original image in the center of the new matrix
# The slice starts at 'padding' and goes up to 'new_rows - padding'
padded_image[padding:new_rows - padding, padding:new_cols - padding] = image

print("Original Image:\n", image)
print("\n Padded Image:\n", padded_image)

Original Image:
 [[0.2431393  0.51969049 0.05839192 0.7396655 ]
 [0.04077804 0.08833915 0.99933226 0.67465722]]

 Padded Image:
 [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.2431393  0.51969049 0.05839192 0.7396655
  0.         0.        ]
 [0.         0.         0.04077804 0.08833915 0.99933226 0.67465722
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [143]:
padded_image.shape

(6, 8)